version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - web
      - auth-service
      - notes-service

  auth-service:
    build: ./auth-service
    expose:
      - "3000"
  
  notes-service:
    build: ./notes-service
    expose:
      - "3001"

  web:
    build: ./web
    expose:
      - "8080"
